name: Вторая практическая работа

on: [workflow_dispatch, push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Запуск тестов
        run: echo "Тесты успешно пройдены!"

  build_project:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Сборка проекта
        run: echo "Сборка успешно завершена!"
