name: Deploy React App

on: [workflow_dispatch, push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Запуск тестов пройден успешно!"


  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run linter
        run: echo "Проверка линт пройдена"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run build
        run: echo "Сборка завершена"
